# Generated by Django 4.2.3 on 2023-07-12 07:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0005_profile_city_profile_date_of_birth_profile_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='matchmodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='re_baseuser', to=settings.AUTH_USER_MODEL)),
                ('match_user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='re_matchuser', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
